export const DUMMY_ALL_ATTRIBUTES: Attribute[] = [
  {
    id: "attr_brand_001",
    name: "Brand",
    slug: "brand",
    type: "TEXT",
    group: "BASIC",
    label: "Product Brand",
    placeholder: "Enter brand name",
    helpText: "The manufacturer or brand name of the product",
    unit: null,
    unitPosition: null,
    options: null,
    validations: [
      { type: "REQUIRED", value: true, message: "Brand is required" },
      { type: "MIN_LENGTH", value: 2, message: "Minimum 2 characters" },
      { type: "MAX_LENGTH", value: 50, message: "Maximum 50 characters" },
    ],
    minValue: null,
    maxValue: null,
    minLength: 2,
    maxLength: 50,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: true,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: true,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 0,
    visibility: "PUBLIC",
    cssClass: "brand-field",
    icon: "/icons/brand.svg",
    status: "ACTIVE",
    metaData: {
      popularBrands: ["Apple", "Samsung", "Nike", "Sony", "LG", "Dell"],
      autoComplete: true,
      suggestions: true,
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_color_001",
    name: "Color",
    slug: "color",
    type: "SELECT",
    group: "BASIC",
    label: "Product Color",
    placeholder: "Select a color",
    helpText: "Choose the color of the product",
    unit: null,
    unitPosition: null,
    options: [
      {
        value: "red",
        label: "Red",
        swatch: { type: "COLOR", value: "#FF0000" },
      },
      {
        value: "blue",
        label: "Blue",
        swatch: { type: "COLOR", value: "#0000FF" },
      },
      {
        value: "green",
        label: "Green",
        swatch: { type: "COLOR", value: "#00FF00" },
      },
      {
        value: "black",
        label: "Black",
        swatch: { type: "COLOR", value: "#000000" },
      },
      {
        value: "white",
        label: "White",
        swatch: { type: "COLOR", value: "#FFFFFF" },
      },
    ],
    validations: [
      { type: "REQUIRED", value: true, message: "Color is required" },
    ],
    minValue: null,
    maxValue: null,
    minLength: null,
    maxLength: null,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: true,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: true,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 1,
    visibility: "PUBLIC",
    cssClass: "color-field",
    icon: "/icons/color.svg",
    status: "ACTIVE",
    metaData: {
      displayType: "swatch",
      multiple: false,
      showColorName: true,
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_size_001",
    name: "Size",
    slug: "size",
    type: "SELECT",
    group: "PHYSICAL",
    label: "Available Sizes",
    placeholder: "Select size",
    helpText: "Choose your size",
    unit: null,
    unitPosition: null,
    options: [
      {
        value: "xs",
        label: "Extra Small (XS)",
        swatch: { type: "TEXT", value: "XS" },
      },
      { value: "s", label: "Small (S)", swatch: { type: "TEXT", value: "S" } },
      { value: "m", label: "Medium (M)", swatch: { type: "TEXT", value: "M" } },
      { value: "l", label: "Large (L)", swatch: { type: "TEXT", value: "L" } },
      {
        value: "xl",
        label: "Extra Large (XL)",
        swatch: { type: "TEXT", value: "XL" },
      },
    ],
    validations: [
      { type: "REQUIRED", value: true, message: "Size is required" },
    ],
    minValue: null,
    maxValue: null,
    minLength: null,
    maxLength: null,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: true,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: true,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 2,
    visibility: "PUBLIC",
    cssClass: "size-field",
    icon: "/icons/size.svg",
    status: "ACTIVE",
    metaData: {
      sizeChart: true,
      sizeSystem: "US/UK",
      sizeType: "clothing",
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_weight_001",
    name: "Weight",
    slug: "weight",
    type: "NUMBER",
    group: "PHYSICAL",
    label: "Product Weight",
    placeholder: "Enter weight",
    helpText: "Weight of the product in kilograms",
    unit: "kg",
    unitPosition: "suffix",
    options: null,
    validations: [
      { type: "REQUIRED", value: true, message: "Weight is required" },
      { type: "MIN_VALUE", value: 0.1, message: "Minimum weight is 0.1 kg" },
      { type: "MAX_VALUE", value: 100, message: "Maximum weight is 100 kg" },
    ],
    minValue: 0.1,
    maxValue: 100,
    minLength: null,
    maxLength: null,
    stepValue: 0.1,
    decimalPlaces: 2,
    isRequired: true,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: false,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 3,
    visibility: "PUBLIC",
    cssClass: "weight-field",
    icon: "/icons/weight.svg",
    status: "ACTIVE",
    metaData: {
      unitSystem: "metric",
      allowDecimal: true,
      showUnit: true,
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_instock_001",
    name: "In Stock",
    slug: "in-stock",
    type: "BOOLEAN",
    group: "INVENTORY",
    label: "In Stock",
    placeholder: null,
    helpText: "Is the product currently in stock?",
    unit: null,
    unitPosition: null,
    options: null,
    validations: [
      { type: "REQUIRED", value: true, message: "Stock status is required" },
    ],
    minValue: null,
    maxValue: null,
    minLength: null,
    maxLength: null,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: true,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: false,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 4,
    visibility: "PUBLIC",
    cssClass: "stock-field",
    icon: "/icons/stock.svg",
    status: "ACTIVE",
    metaData: {
      trueLabel: "In Stock",
      falseLabel: "Out of Stock",
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_release_001",
    name: "Release Date",
    slug: "release-date",
    type: "DATE",
    group: "MARKETING",
    label: "Release Date",
    placeholder: "Select release date",
    helpText: "When was this product released?",
    unit: null,
    unitPosition: null,
    options: null,
    validations: [
      { type: "REQUIRED", value: false, message: "Release date is optional" },
    ],
    minValue: null,
    maxValue: null,
    minLength: null,
    maxLength: null,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: false,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: false,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 5,
    visibility: "PUBLIC",
    cssClass: "date-field",
    icon: "/icons/date.svg",
    status: "ACTIVE",
    metaData: {
      format: "YYYY-MM-DD",
      minDate: "2000-01-01",
      maxDate: "2025-12-31",
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_features_001",
    name: "Features",
    slug: "features",
    type: "MULTISELECT",
    group: "TECHNICAL",
    label: "Product Features",
    placeholder: "Select features",
    helpText: "Select all applicable features",
    unit: null,
    unitPosition: null,
    options: [
      { value: "waterproof", label: "Waterproof" },
      { value: "wireless", label: "Wireless" },
      { value: "bluetooth", label: "Bluetooth" },
      { value: "wifi", label: "Wi-Fi" },
      { value: "gps", label: "GPS" },
      { value: "touchscreen", label: "Touchscreen" },
    ],
    validations: [
      { type: "MIN_LENGTH", value: 1, message: "Select at least one feature" },
      {
        type: "MAX_LENGTH",
        value: 6,
        message: "Cannot select more than 6 features",
      },
    ],
    minValue: null,
    maxValue: null,
    minLength: 1,
    maxLength: 6,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: false,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: false,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 6,
    visibility: "PUBLIC",
    cssClass: "features-field",
    icon: "/icons/features.svg",
    status: "ACTIVE",
    metaData: {
      displayType: "checkbox",
      maxSelect: 6,
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_price_001",
    name: "Price",
    slug: "price",
    type: "PRICE",
    group: "PRICING",
    label: "Product Price",
    placeholder: "Enter price",
    helpText: "Price in BDT",
    unit: "৳",
    unitPosition: "prefix",
    options: null,
    validations: [
      { type: "REQUIRED", value: true, message: "Price is required" },
      { type: "MIN_VALUE", value: 0, message: "Price cannot be negative" },
      {
        type: "MAX_VALUE",
        value: 1000000,
        message: "Price cannot exceed 1,000,000",
      },
    ],
    minValue: 0,
    maxValue: 1000000,
    minLength: null,
    maxLength: null,
    stepValue: 100,
    decimalPlaces: 2,
    isRequired: true,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: false,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 7,
    visibility: "PUBLIC",
    cssClass: "price-field",
    icon: "/icons/price.svg",
    status: "ACTIVE",
    metaData: {
      currency: "BDT",
      showDiscount: true,
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_discount_001",
    name: "Discount",
    slug: "discount",
    type: "PERCENTAGE",
    group: "PRICING",
    label: "Discount Percentage",
    placeholder: "Enter discount",
    helpText: "Discount percentage for this product",
    unit: "%",
    unitPosition: "suffix",
    options: null,
    validations: [
      { type: "MIN_VALUE", value: 0, message: "Discount cannot be negative" },
      { type: "MAX_VALUE", value: 100, message: "Discount cannot exceed 100%" },
    ],
    minValue: 0,
    maxValue: 100,
    minLength: null,
    maxLength: null,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: false,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: false,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 8,
    visibility: "PUBLIC",
    cssClass: "discount-field",
    icon: "/icons/discount.svg",
    status: "ACTIVE",
    metaData: {
      allowDecimal: false,
      showAsBadge: true,
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "attr_warranty_001",
    name: "Warranty",
    slug: "warranty",
    type: "SELECT",
    group: "WARRANTY",
    label: "Warranty Period",
    placeholder: "Select warranty",
    helpText: "Warranty period for this product",
    unit: null,
    unitPosition: null,
    options: [
      { value: "no", label: "No Warranty" },
      { value: "6months", label: "6 Months" },
      { value: "1year", label: "1 Year" },
      { value: "2years", label: "2 Years" },
      { value: "3years", label: "3 Years" },
      { value: "5years", label: "5 Years" },
      { value: "lifetime", label: "Lifetime" },
    ],
    validations: [
      {
        type: "REQUIRED",
        value: true,
        message: "Warranty information is required",
      },
    ],
    minValue: null,
    maxValue: null,
    minLength: null,
    maxLength: null,
    stepValue: 1,
    decimalPlaces: 0,
    isRequired: true,
    isUnique: false,
    isFilterable: true,
    isVisible: true,
    isVariation: false,
    isSearchable: true,
    isGlobal: true,
    sortOrder: 9,
    visibility: "PUBLIC",
    cssClass: "warranty-field",
    icon: "/icons/warranty.svg",
    status: "ACTIVE",
    metaData: {
      warrantyType: "manufacturer",
      coverage: "parts and labor",
    },
    values: [],
    categories: [],
    originCategory: null,
    originCategoryId: null,
    createdBy: "admin@system.com",
    updatedBy: "admin@system.com",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    deletedAt: null,
  },
];
